"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.default = ReportsData;
var jsx_runtime_1 = require("react/jsx-runtime");
var card_1 = require("../components/ui/card");
var recharts_1 = require("recharts");
var react_1 = require("react");
function ReportsData(_a) {
    var data = _a.data;
    var _b = (0, react_1.useState)(data.trends), trends = _b[0], setTrends = _b[1];
    return ((0, jsx_runtime_1.jsxs)("div", { children: [data.parameters.length > 0 && ((0, jsx_runtime_1.jsx)(card_1.Card, { className: "", children: (0, jsx_runtime_1.jsxs)(card_1.CardContent, { children: [(0, jsx_runtime_1.jsx)("h2", { className: "text-xl font-semibold mb-2", children: "Extracted Health Parameters" }), (0, jsx_runtime_1.jsxs)("table", { className: "w-full text-left", children: [(0, jsx_runtime_1.jsx)("thead", { children: (0, jsx_runtime_1.jsxs)("tr", { children: [(0, jsx_runtime_1.jsx)("th", { className: "border p-2", children: "Parameter" }), (0, jsx_runtime_1.jsx)("th", { className: "border p-2", children: "Value" }), (0, jsx_runtime_1.jsx)("th", { className: "border p-2", children: "Unit" }), (0, jsx_runtime_1.jsx)("th", { className: "border p-2", children: "Range" })] }) }), (0, jsx_runtime_1.jsx)("tbody", { children: data.parameters.map(function (param, idx) { return ((0, jsx_runtime_1.jsxs)("tr", { children: [(0, jsx_runtime_1.jsx)("td", { className: "border p-2", children: param.parameter }), (0, jsx_runtime_1.jsx)("td", { className: "border p-2", children: param.value }), (0, jsx_runtime_1.jsx)("td", { className: "border p-2", children: param.unit }), (0, jsx_runtime_1.jsx)("td", { className: "border p-2", children: param.referenceRange })] }, idx)); }) })] })] }) })), trends.length > 0 && ((0, jsx_runtime_1.jsx)(card_1.Card, { className: "mt-6", children: (0, jsx_runtime_1.jsxs)(card_1.CardContent, { children: [(0, jsx_runtime_1.jsx)("h2", { className: "text-xl font-semibold mb-2", children: "Simple Trends" }), (0, jsx_runtime_1.jsx)(recharts_1.ResponsiveContainer, { width: "100%", height: 300, children: (0, jsx_runtime_1.jsxs)(recharts_1.LineChart, { data: trends, children: [(0, jsx_runtime_1.jsx)(recharts_1.XAxis, { dataKey: "date" }), (0, jsx_runtime_1.jsx)(recharts_1.YAxis, {}), (0, jsx_runtime_1.jsx)(recharts_1.Tooltip, {}), (0, jsx_runtime_1.jsx)(recharts_1.CartesianGrid, { stroke: "#eee" }), (0, jsx_runtime_1.jsx)(recharts_1.Line, { type: "monotone", dataKey: "Hemoglobin", stroke: "#8884d8" }), (0, jsx_runtime_1.jsx)(recharts_1.Line, { type: "monotone", dataKey: "Cholesterol", stroke: "#82ca9d" })] }) })] }) }))] }));
}
